InputDevice: Simplify RcTypeControl class
Do not use pathExists but use directly os.path.exists

Also, make sure that rctype has value else write the default 0, this prevents
the following error to happen when switching RC.

TypeError: %d format: a number is required, not NoneType

Adapted from:
OpenPLi/enigma2@10d3a81